version: "3.3"

services:
  app:
    build: .
    command: bash start.sh
    restart: on-failure
    ports:
      - "13:13"
      - "9275:9275"

networks:
  default:
    external: true
    name: network11
